fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-ast   # checks Python syntax
    - id: check-merge-conflict  # checks for no merge conflict strings
    - id: mixed-line-ending  # normalizes line endings
    - id: no-commit-to-branch  # prevents committing to main

- repo: https://github.com/psf/black
  rev: 22.6.0  # IMPORTANT: keep this aligned with the black version in pyproject.toml
  hooks:
  - id: black-jupyter

- repo: local
  hooks:
    - id: tutorials-markdown
      name: Markdown version of the tutorials
      entry: python scripts/generate_markdowns.py
      language: system
      types: [jupyter]  

-   repo: meta
    hooks:
    -   id: identity      