[config]
layout = "tutorial"
toc = true 
colab = "https://colab.research.google.com/github/deepset-ai/haystack-tutorials/blob/main/tutorials/"

[[tutorial]]
title = "Build Your First Question Answering System"
description = "Get Started by creating a Retriever Reader pipeline."
level = "beginner"
weight = 10
notebook = "01_build_your_first_question_answering_system.ipynb"
aliases = ["first-qa-system"]
slug = "01_basic_qa_pipeline"

[[tutorial]]
title = "Fine-Tune a Reader"
description = "Improve the performance of your Reader by performing fine-tuning."
level = "intermediate"
weight = 50
notebook = "02_finetune_a_reader.ipynb"
aliases = ["fine-tuning-a-model", "02_finetune_a_model_on_your_data", "fine-tune-a-model"]
slug = "02_finetune_a_model_on_your_data"

[[tutorial]]
title = "Build a Scalable Question Answering System"
description = "Create a scalable Retriever Reader pipeline that uses an ElasticsearchDocumentStore."
level = "beginner"
weight = 15
notebook = "03_build_a_scalable_question_answering_system.ipynb"
aliases = ["without-elasticsearch"]
slug = "03_scalable_qa_pipeline"

[[tutorial]]
title = "Utilizing Existing FAQs for Question Answering"
description = "Create a smarter way to answer new questions using your existing FAQ documents."
level = "beginner"
weight = 20
notebook = "04_FAQ_style_QA.ipynb"
aliases = ["existing-faqs"]

[[tutorial]]
title = "Evaluation of a QA System"
description = "Learn how to evaluate the performance of individual nodes as well as entire pipelines."
level = "advanced"
weight = 100
notebook = "05_Evaluation.ipynb"
aliases = ["evaluation"]

[[tutorial]]
title = "Better Retrieval with Embedding Retrieval"
description = "Use Transformer based dense Retrievers to improve your system’s performance."
level = "intermediate"
weight = 55
notebook = "06_Better_Retrieval_via_Embedding_Retrieval.ipynb"
aliases = ["embedding-retrieval"]

[[tutorial]]
title = "Generative QA with Retrieval-Augmented Generation"
description = "Try out a generative model in place of the extractive Reader."
level = "intermediate"
weight = 60
notebook = "07_RAG_Generator.ipynb"
aliases = ["retrieval-augmented-generation"]

[[tutorial]]
title = "Preprocessing Your Documents"
description = "Start converting, cleaning, and splitting Documents using Haystack’s preprocessing capabilities."
level = "beginner"
weight = 25
notebook = "08_Preprocessing.ipynb"
aliases = ["preprocessing"]

[[tutorial]]
title = "Training Your Own Dense Passage Retrieval Model"
description = "Learn about training a Dense Passage Retrieval model and the data needed to do so."
level = "advanced"
weight = 110
notebook = "09_DPR_training.ipynb"
aliases = ["train-dpr"]

[[tutorial]]
title = "Question Answering on a Knowledge Graph"
description = "Experiment with a question answering system that draws upon knowledge graph.h"
level = "advanced"
weight = 120
notebook = "10_Knowledge_Graph.ipynb"
aliases = ["knowledge-graph"]

[[tutorial]]
title = "How to Use Pipelines"
description = "Learn about the many ways which you can route queries through the nodes in a pipeline."
level = "intermediate"
weight = 65
notebook = "11_Pipelines.ipynb"
aliases = ["pipelines"]

[[tutorial]]
title = "Generative QA with LFQA"
description = "Try out a generative model in place of the extractive Reader."
level = "intermediate"
weight = 70
notebook = "12_LFQA.ipynb"
aliases = ["lfqa"]

[[tutorial]]
title = "Question Generation"
description = "Generate a set of questions that can be answered by a given Document."
level = "intermediate"
weight = 75
notebook = "13_Question_generation.ipynb"
aliases = ["question-generation"]

[[tutorial]]
title = "Query Classifier"
description = "Classify incoming queries so that they can be routed to the nodes that are best at handling them."
level = "intermediate"
weight = 80
notebook = "14_Query_Classifier.ipynb"
aliases = ["query-classifier"]

[[tutorial]]
title = "Open-Domain QA on Tables"
description = "Perform question answering on tabular data."
level = "advanced"
weight = 130
notebook = "15_TableQA.ipynb"
aliases = ["table-qa"]

[[tutorial]]
title = "Document Classification at Index Time"
description = "Generate and attach classification labels to your Documents when indexing."
level = "intermediate"
weight = 85
notebook = "16_Document_Classifier_at_Index_Time.ipynb"
aliases = ["doc-class-index"]

[[tutorial]]
title = "Make Your QA Pipelines Talk!"
description = "Convert text Answers into speech."
level = "intermediate"
weight = 90
notebook = "17_Audio.ipynb"
aliases = ["audio"]

[[tutorial]]
title = "Generative Pseudo Labeling for Domain Adaptation"
description = "Use a Retriever and a query generator to perform unsupervised domain adaptation."
level = "advanced"
weight = 140
notebook = "18_GPL.ipynb"
aliases = ["gpl"]

[[tutorial]]
title = "Text-To-Image Search Pipeline with Multimodal Retriever"
description = "Use a MultiModalRetriever to build a cross-modal search pipeline."
level = "intermediate"
weight = 95
notebook = "19_Text_to_Image_search_pipeline_with_MultiModal_Retriever.ipynb"
aliases = ["multimodal"]

[[tutorial]]
title = "Distill a Reader"
description = "Transfer a Reader's question answering ability to a smaller, more efficient model."
level = "intermediate"
weight = 115
notebook = "21_distill_a_reader.ipynb"
aliases = ["distill-reader"]